CREATE TABLE TelcoCustomerChurn (
	customerID TEXT,
	gender TEXT,
	SeniorCitizen INTEGER,
	Partner TEXT,
	Dependents TEXT,
	tenure INTEGER,
	PhoneService TEXT,
	MultipleLines TEXT,
	InternetService TEXT,
	OnlineSecurity TEXT,
	OnlineBackup TEXT,
	DeviceProtection TEXT,
	TechSupport TEXT,
	StreamingTV TEXT,
	StreamingMovies TEXT,
	Contract TEXT,PaperlessBilling TEXT,
	PaymentMethod TEXT,
	MonthlyCharges REAL,
	TotalCharges REAL,
	Churn TEXT
)